Add tooltip using instruction
js-tasks-ru/htmlcss-20220919_anna881 pull request #10
Opened 2022-10-08 13:27 UTC by navoznova

2022-10-08 13:28 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-08 15:11 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-08 15:23 UTC, GSemikozov requested changes

2022-10-08 15:23 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +body {
глобальные / вспомогательные стили не нужно добавлять в файл стилей компонента - если глобальные то в main.css, если вспомогательные (только для этой страницы) - то в тег style самой страницы

2022-10-08 16:30 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-10 08:36 UTC, GSemikozov approved these changes

2022-10-10 08:37 UTC, merged