Add modal window
js-tasks-ru/htmlcss-20220919_anna881 pull request #11
Opened 2022-10-09 07:57 UTC by navoznova

2022-10-09 07:58 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-10 08:36 UTC, GSemikozov requested changes

2022-10-10 08:36 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.open-modal {
уже есть button button_primary , это лишнее

2022-10-10 08:43 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-10 08:46 UTC, GSemikozov approved these changes

2022-10-10 08:46 UTC, merged