Add mobile style for main page
js-tasks-ru/htmlcss-20220919_anna881 pull request #12
Opened 2022-10-11 07:02 UTC by navoznova

add @media for the main page

2022-10-11 07:03 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-12 11:18 UTC, GSemikozov requested changes

2022-10-12 11:18 UTC, GSemikozov commented on components/card/card.css
> +        font-family: 'Inter';
font-family + font-style + color и др - они ведь не меняются по сравнению с десктопом?

2022-10-15 03:28 UTC, navoznova commented on components/card/card.css
> +        font-family: 'Inter';
да, не меняются, спасибо, что заметил

2022-10-15 03:32 UTC, navoznova commented on components/card/card.css
> +        font-family: 'Inter';
Может в фигме в макете ошибка, там у десктопа и у мобильки разные стили
Десктоп
font-family: 'Roboto';
font-style: normal;
font-weight: 500;
font-size: 21px;
line-height: 25px;
text-align: center;
color: #212429;

Мобильная
font-family: 'Inter';
font-style: normal;
font-weight: 400;
font-size: 16px;
line-height: 24px;
text-align: center;
color: #212429;

2022-10-16 21:08 UTC, GSemikozov approved these changes, later dismissed

2022-10-16 21:08 UTC, GSemikozov commented on components/card/card.css
> +        font-family: 'Inter';
да, принято

2022-10-16 21:08 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2022-10-18 08:19 UTC, GSemikozov approved these changes

2022-10-18 08:19 UTC, merged