Add mobile style for component page
js-tasks-ru/htmlcss-20220919_anna881 pull request #13
Opened 2022-10-11 07:54 UTC by navoznova

2022-10-11 07:54 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-12 11:19 UTC, GSemikozov requested changes

2022-10-12 11:19 UTC, GSemikozov commented on components/content/content.css
> +    width: 825px;
ширину и высоту такой секции не нужно ограничивать / жестко фиксировать)

2022-10-12 11:19 UTC, GSemikozov commented on components/template/template.css
> +body {
лишние глобальные стили в компоненте

2022-10-12 11:19 UTC, GSemikozov commented on components/template/template.css
> +.template__footer {
лучше добавить отдельный элемент в футере для текста

2022-10-15 03:56 UTC, navoznova commented on components/content/content.css
> +    width: 825px;
у меня затык, когда я убираю здесь высоту, у меня футер не прижимается к низу.
grid auto 1fr auto не дает результата

2022-10-15 03:56 UTC, navoznova commented on components/template/template.css
> +body {
fix

2022-10-15 04:11 UTC, navoznova commented on components/content/content.css
> +    width: 825px;
fix

2022-10-15 04:21 UTC, navoznova commented on components/template/template.css
> +.template__footer {
done

2022-10-16 21:06 UTC, GSemikozov approved these changes

2022-10-16 21:06 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2022-10-16 21:10 UTC, GSemikozov approved these changes

2022-10-16 21:10 UTC, merged