03 lection1 button
js-tasks-ru/htmlcss-20220919_anna881 pull request #3
Opened 2022-09-26 03:22 UTC by navoznova

Add 3 buttons in three different statuses -- default, hover, and disabled

2022-09-26 03:22 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-09-27 09:18 UTC, GSemikozov requested changes

2022-09-27 09:18 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    width: 189px;
ширину жестко ограничивать не нужно

2022-09-27 09:18 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    font-size: 16px;
не хватает font-family

2022-09-27 09:18 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button__primary {
модификаторы пишем через 1 нижнее подчеркивание

2022-09-29 07:49 UTC, GSemikozov approved these changes

2022-09-29 07:49 UTC, merged