Add histogram
js-tasks-ru/htmlcss-20220919_anna881 pull request #8
Opened 2022-10-03 12:49 UTC by navoznova

2022-10-03 12:49 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-03 18:43 UTC, GSemikozov requested changes

2022-10-03 18:43 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    width: 9px;
flex-basis

2022-10-03 18:43 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    height: 100%;
лишнее (если с сервера получим null, а покажем при этом 100% - будет обманом), удалим

2022-10-04 03:47 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-04 03:49 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-05 06:11 UTC, GSemikozov requested changes

2022-10-05 06:11 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.orders {
если хотим отдельный блок orderds - то надо унести в отдельный файл. Но - скорее всего все-таки речь об элементе блока гистограммы, поэтому - .histogram__orders, .histogram__title, .histogram__subtitle и тд

2022-10-05 07:08 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-05 08:19 UTC, GSemikozov approved these changes

2022-10-05 08:19 UTC, merged